#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

[[ -n "${PROVIDER:-}" ]] && pritunl-link provider "$PROVIDER"
[[ -n "${UNIFI_CONTROLLER:-}" ]] && pritunl-link unifi-controller "$UNIFI_CONTROLLER"
[[ -n "${UNIFI_SITE:-}" ]] && pritunl-link unifi-site "$UNIFI_SITE"
[[ -n "${UNIFI_USERNAME:-}" ]] && pritunl-link unifi-username "$UNIFI_USERNAME"
[[ -n "${UNIFI_PASSWORD:-}" ]] && pritunl-link unifi-password "$UNIFI_PASSWORD"
[[ -n "${VERIFY_OFF:-}" ]] && sudo pritunl-link verify-off

if [[ -n "$URLS" ]]; then
    pritunl-link clear
    URL=$(echo "$URLS" | tr "," "\n")
    for i in $URL; do
      pritunl-link add "$i"
    done

    pritunl-link start
else
  echo "No URL provided. There is no server to connect to"
fi
